### ISSUE TITLE
Default app name is invalid for npm

### ISSUE THREAD

**Issue by derekwheee** [pierceray/generator-johnny-five#2]
The default appname (`this.appname`) for Yeoman is basically the current working directory with any non-word or non-whitespace characters replaced with spaces. See https://github.com/yeoman/generator/blob/master/lib/base.js#L757-768. You'll need to transform that before sending it to package.json.

npm packages don't allow whitespace in the name, so it's invalid in the package.json ("Project Name" is also invalid).

**Comment by Resseguie** [comment]
Thanks, that explains why I was getting errors when in a directory name with a dash in it.

**Comment by pierceray** [comment]
As I read this, doing a simple `this.appname.replace(/\s+/g, '')` should get the results we are looking for.
