### ISSUE TITLE
Generate test "stuff"

### ISSUE THREAD

**Issue by rwaldron** [pierceray/generator-johnny-five#4]
- Add a test/ directory to template
- Prompt for preferred test framework (probably from a list, see next bullet)
- Generate a base line test file from a set of premade templates for popular test frameworks
- Stubs: 
  - Johnny-Five?
  - ... What else?

**Comment by pierceray** [comment]
I don't know that much about unit testing with with node, nor the popular frameworks to use with it.  Is it just `mocha/sinon/chai` and `nodeunit`?  This seems like it would dictate building up a Gruntfile as well.

**Comment by rwaldron** [comment]
I'm not really sure what the solution looks like here, I just wanted to file it so it was "out there" for everyone to think about

**Comment by pierceray** [comment]
@jared-stilwell any input here?

**Comment by pierceray** [comment]
I'm going to work on getting a basic Karma/Mocha/Sinon/Chai setup going for this.

**Comment by pierceray** [comment]
After some consideration I'm going to go with Nodeunit for the initial implementation.  It's much easier to setup.

**Comment by pierceray** [comment]
Fixed with 003f1c8
