### ISSUE TITLE
Create an IO-Plugins prompt

### ISSUE THREAD

**Issue by rwaldron** [pierceray/generator-johnny-five#7]
Should prompt user to select a platform, which will then include the correct io-plugin.

Refactoring this: https://github.com/pierceray/generator-johnny-five/blob/master/generators/app/index.js#L26-L36 to be like this: https://github.com/pierceray/generator-johnny-five/blob/master/generators/app/index.js#L37-L53 Then we can break this:  https://github.com/pierceray/generator-johnny-five/blob/master/generators/app/templates/_index.js#L2-L9 out to a template and load all of the supported IO-Plugins here: https://github.com/pierceray/generator-johnny-five/blob/master/generators/app/index.js#L71-L75

**Comment by pierceray** [comment]
Can you use multiple IO plugin simultaneously?  Or would a [list](https://github.com/SBoudrias/Inquirer.js#list----type-list-) make more sense?

**Comment by rwaldron** [comment]
Oh, I didn't realize that distinction. It should be whatever format enforces a single choice from many

**Comment by pierceray** [comment]
Switched to use a list for the base project type.

fixed with 2323681
